### ISSUE TITLE
Release not published

### ISSUE THREAD

**Issue by strogonoff** [glossarist/glossarist-desktop#102]
I don’t see 1.6.17 release, even though CI flows completed successfully (https://github.com/glossarist/glossarist-desktop/actions/runs/215395828)

**Comment by strogonoff** [comment]
Upon rerun, another issue as CI failed at notarization (“Failed to upload app to Apple's notarization servers: Server returned an invalid MIME type: text/plain, body: Unauthenticated”)

**Comment by ronaldtse** [comment]
The latest build worked. Maybe it was a network issue... 

https://github.com/glossarist/glossarist-desktop/actions/runs/215395828

**Comment by ronaldtse** [comment]
Wait... notarization worked but it's not published?? We don't have the tag??

```
Notarizing org.glossarist.desktop found at /Users/runner/work/glossarist-desktop/glossarist-desktop/dist/mac/Glossarist.app
1062
Done notarizing org.glossarist.desktop
1063
  • building        target=DMG arch=x64 file=dist/glossarist-desktop-1.6.17.dmg
1064
  • building block map  blockMapFile=dist/glossarist-desktop-1.6.17.dmg.blockmap
1065
  • publishing      publisher=Github (owner: glossarist, project: glossarist-desktop, version: 1.6.17)
1066
  • uploading       file=glossarist-desktop-1.6.17.dmg.blockmap provider=GitHub
1067
  • uploading       file=glossarist-desktop-1.6.17.dmg provider=GitHub
1068
  • skipped publishing  file=glossarist-desktop-1.6.17.dmg.blockmap reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v1.6.17 version=1.6.17
1069
  • skipped publishing  file=glossarist-desktop-1.6.17.dmg reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v1.6.17 version=1.6.17
1070
  • skipped publishing  file=latest-mac.yml reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v1.6.17 version=1.6.17
1071
```

**Comment by ronaldtse** [comment]
AHHH the tag was `1.6.17` but should have been `v1.6.17` that's why the release upload didn't work. @strogonoff can you push a new commit and re-tag 1.6.17? Thanks!

**Comment by ronaldtse** [comment]
Re-running release now to see if it works.

**Comment by strogonoff** [comment]
I think that was totally my fault then. I was tagging NPM libraries differently.

**Comment by strogonoff** [comment]
Apparently fixed with your tag Ronald, I see the release now, will remember to name tags properly next time

**Comment by ronaldtse** [comment]
Awesome, thanks!
