### ISSUE TITLE
Build Linux

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#113]
Right now we’re not building on Linux. We need to release a Linux build using GitHub Actions. 

In addition, detection on the glossary.org site is mistaking Linux browsers as from Windows. We need to fix that.

**Comment by ronaldtse** [comment]
@webdev778 is going to handle this, thanks.

**Comment by ronaldtse** [comment]
@webdev778 reports this issue after compiling on Ubuntu (which succeeds), but crashes when run:

![image](https://user-images.githubusercontent.com/11865/92201603-9386e480-eeaf-11ea-8766-e40026d615f6.png)

He's going to handle this task.

**Comment by webdev778** [comment]
the issue was a mistake by me, I should run dist command after the compile. please disregard this.

**Comment by strogonoff** [comment]
Linux build works, but it looks like publishing the resulting snap fails… (see latest issues)

**Comment by webdev778** [comment]
yeah, I noticed it, working on it.

**Comment by webdev778** [comment]
Just sent the PR again after you merged. please merge and let me know if it works

**Comment by strogonoff** [comment]
Snap packages are built (https://github.com/glossarist/glossarist-desktop/commit/c65b04b4ff2213c1c0c9fdad3461a58a92f9210e, https://github.com/glossarist/glossarist-desktop/commit/0acb82efb3911be71f4848732e40b2b72b8b66d5)
