### ISSUE TITLE
Snapcraft token

### ISSUE THREAD

**Issue by strogonoff** [glossarist/glossarist-desktop#119]
Should we have a Snapcraft account to build snap package using Ubuntu’s (apparently) preferred method?

This is according to the GHA action we’re using:

- https://github.com/samuelmeuli/action-electron-builder#snapcraft
- https://github.com/samuelmeuli/action-snapcraft#log-in

**Comment by strogonoff** [comment]
If this is possible, let’s have the Snapcraft token available as `SNAPCRAFT_TOKEN` (uppercase) in GHA using repository secret variables? (cc @ronaldtse)

**Comment by ronaldtse** [comment]
OK I will setup a Snap account for Glossarist

**Comment by ronaldtse** [comment]
Available here now: SNAPCRAFT_RELEASE_LOGIN
