### ISSUE TITLE
Snap releases: register our snap

### ISSUE THREAD

**Issue by strogonoff** [glossarist/glossarist-desktop#121]
Releasing 1.6.23 [failed](https://github.com/glossarist/glossarist-desktop/runs/1070199588?check_suite_focus=true#step:6:1170) with an error:

> This snap is not registered. Register the snap and try again.

@ronaldtse if you are in that context, could you check what’s needed to register a snap?

**Comment by ronaldtse** [comment]
Registered `glossarist` snap.
