### ISSUE TITLE
Linux: make Ubuntu Snap build work

### ISSUE THREAD

**Issue by strogonoff** [glossarist/glossarist-desktop#122]
Latest Ubuntu build failed with an error:

```
- macaroon-permission-required: Package-restricted permission does not include snap-id Jxu47j62oxgVbSHApCcIAy5s5XchoxYZ
```

Need to look into that.

**Comment by ronaldtse** [comment]
It looks like the snap token didn’t work with the snap package?

**Comment by strogonoff** [comment]
Linux build works, the issue is when publishing to Snapcraft. I’m disabling Snapcraft publication.

**Comment by strogonoff** [comment]
Linux build works.
