### ISSUE TITLE
Provide documentation for simple setup

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#126]
For people who do not have an existing term repo, we need to allow them to set one up.

1. Documentation on how to create a git repo e.g. GitHub
2. Explain how to install Glossarist
3. Initial setup of Glossarist: how to link Glossarist to the repo
4. How to setup the first concept

**Comment by strogonoff** [comment]
* Documentation on how to create a git repo e.g. GitHub

https://www.glossarist.org/docs/adopt/2-infrastructure/

* Explain how to install Glossarist

https://www.glossarist.org/docs/desktop/getting-started/initial-setup/

* Initial setup of Glossarist: how to link Glossarist to the repo

https://www.glossarist.org/docs/desktop/getting-started/initial-setup/

* How to setup the first concept

https://github.com/glossarist/glossarist.org/issues/7
