### ISSUE TITLE
Allow multiple types of relationships

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#137]
<img width="279" alt="Screen Shot 2020-09-09 at 12 35 40 PM" src="https://user-images.githubusercontent.com/11865/92554885-fa821000-f298-11ea-8747-932f7dde6264.png">

Relationship types
* domain (ISO, SKOS: broader)
* narrower (SKOS: narrower)
* related (we have this already, SKOS: related)
* identical (SKOS: exactMatch)

Relationship values:
* allow external URLs as relationships

**Comment by ronaldtse** [comment]
Would be great if we can allow URLs as relationship targets (which can use identical, parent, child, related). Thanks!

**Comment by strogonoff** [comment]
I’m going to “won’t fix” this, because our model is different than described—see https://www.glossarist.org/docs/desktop/topics/concept-relationships/. External relationships will be tracked in a different issue

**Comment by ronaldtse** [comment]
In #140 now.
