### ISSUE TITLE
(Was URGENT) Unable to push accepted CR changes

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#147]
In https://github.com/geolexica/isotc211-glossary, the TMG convener was able to accept + resolve, and see the new translated term, but the data is unable to upload to the repository.

In a screen share it is confirmed that the CR is accepted, the local repository works (the new term is accepted and showing in List view).

**Comment by ronaldtse** [comment]
UPDATE: a GitHub auth token may not have permissions to push data? Problem is solved for now by using password authentication.

Maybe we need some interface to test whether the access credentials work? e.g. push a new branch, and delete it.

**Comment by strogonoff** [comment]
> UPDATE: a GitHub auth token may not have permissions to push data? Problem is solved for now by using password authentication.
> 
> Maybe we need some interface to test whether the access credentials work? e.g. push a new branch, and delete it.

A token with “repo” scope is enough, unless there was a recent change in GitHub logic.

**Comment by strogonoff** [comment]
I believe these things should be filed in https://github.com/geolexica/isotc211-glossary-support/issues, as often (like in this case) they are issues outside of Glossarist Desktop but issues pertaining to infrastructure/integration

**Comment by strogonoff** [comment]
Moved to https://github.com/geolexica/isotc211-glossary-support/issues/2
