### ISSUE TITLE
git Branch "master" is hardcoded

### ISSUE THREAD

**Issue by jastram** [glossarist/glossarist-desktop#170]
Just tried to get started with glossarist. Turns out that "master" is hardcoded as the name for the repository branch. However, gitHub changed the default name to "main" a while ago.

I solved this by renaming the branch from main back to master. A better solution would be to request the branch name and to prepopulate that textbox with "main".

**Comment by strogonoff** [comment]
We are moving from standalone Glossarist Desktop to another way of providing an interface for terminology management (in accordance with the same principles). Glossarist Desktop is not maintained anymore, the need to make it clear in online materials and provide a migration guide is acknowledged.

**Comment by jastram** [comment]
Hi Anton – thank you for the update. Some context – I started to collaborate with Ron Tse and some other folks on a publishing pilot, and he suggested to use Glossarist. This aligns with my own activities (https://www.semiant.com).

Do you have time for a 15-minute conversation to help me understand Glossarist better? If so, you can pick some time here: https://calendly.com/formalmind/jastram

Or is there someone else I should talk to?

Thanks! 
- Michael
