### ISSUE TITLE
CR containing revision of "french" translation cannot be "accepted" after accepting a previous revision change

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#18]
Steps:

1. Create change request
2. Modify the term in English for term ID A
3. Add a translation in French for term ID B
4. Go to Review panel
5. Accept the change for term ID A
6. Accept the change for term ID B

Once you click the "accept revision" for Term ID B, the spinner doesn't go away while the "accept revision" button is kept in the "pressed down" state. 

Changing panels will re-enable the "accept revision" button but the resulting change doesn't seem to be incorporated in the git commits.

**Comment by strogonoff** [comment]
Unable to reproduce, but will try from clean slate. 

@ronaldtse was this the first CR ever created during app runtime, or there was another CR created earlier?

**Comment by ronaldtse** [comment]
First CR created during app runtime (first app run).

**Comment by strogonoff** [comment]
I was afraid of these cases. There were not enough error handlers at this time in CR implementation, and an intermittent error may not have been reported properly.

@ronaldtse  Can I ask to attach to this issue the `renderer.log` and `main.log` files, located here: `/Users/<your local username>/Library/Logs/Glossarist`?

**Comment by ronaldtse** [comment]
[Glossarist.zip](https://github.com/glossarist/glossarist-desktop/files/4819681/Glossarist.zip)

**Comment by strogonoff** [comment]
Relevant part, for my future reference when adding handling / updating logic:

```
[2020-06-23 16:17:49.416] [error] Glossarist: Failed to save revision, unable to locate concept language entry 1621 fra
[2020-06-23 16:17:49.417] [error] C/ipc: Error handling request to model-concepts-create-revision! Error: Failed to save revision: Unable to read localized concept entry: Error: Failed to save revision: Unable to read localized concept entry
    at Tr.newRevisionID [as saveRevision] (/Applications/Glossarist.app/Contents/Resources/app.asar/webpack:/src/main/concept-manager.ts:87:13)
    at result (/Applications/Glossarist.app/Contents/Resources/app.asar/webpack:/src/main/concept-manager.ts:263:16)
    at /Applications/Glossarist.app/Contents/Resources/app.asar/webpack:/node_modules/coulomb/ipc/main.js:24:38
    at electron/js2c/browser_init.js:5822:30}
```

**Comment by strogonoff** [comment]
@ronaldtse, unfortunately logs do not write application version (which is an oversight to be corrected), can you confirm you used `1.4.0-pre3`, not `pre2` when doing this?

**Comment by strogonoff** [comment]
(If it was in `pre2`, then the corresponding issue might have been already fixed)

**Comment by strogonoff** [comment]
Somehow parent revision was passed, even though first translation revision in French was being created ([saveRevision()](https://github.com/glossarist/glossarist-desktop/blob/master/src/main/concept-manager.ts#L85)).

Will need to add extra checks that, when new translation is created, [detected parent revision](https://github.com/glossarist/glossarist-desktop/blob/master/src/renderer/home/modules/review.tsx#L150) is empty.

Parent revision is [passed from currently selected global revision](https://github.com/glossarist/glossarist-desktop/blob/master/src/renderer/home/modules/translate.tsx#L177), which actually _can_ have stale value. This worked for regular Edit module, but not for Translate module. Translate module should not pass `ctx.revisionID` when a new translation is created.

**Comment by ronaldtse** [comment]
Pre3 with completely clean setup.
