### ISSUE TITLE
Translate compare side by side option missing

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#28]
In the Translate view, there is a "compare side by side button" to compare two languages.
<img width="1312" alt="Screen Shot 2020-06-25 at 9 41 47 PM" src="https://user-images.githubusercontent.com/11865/85730958-ac934c80-b72c-11ea-927c-be69d766b200.png">

In the Review view, there is only the "comparison target" mechanisms to compare the translation.
<img width="1312" alt="Screen Shot 2020-06-25 at 9 41 31 PM" src="https://user-images.githubusercontent.com/11865/85730923-a309e480-b72c-11ea-9e20-e4af53f33e8d.png">

It would be great if these two tabs work in a consistent way.

Most importantly, these two cases need to be handled:

When the administrator is reviewing translations:
1. If there is a previous translation, we want to compare with the previous translation. If there is no previous translation, there is no point to do a "compare".
2. The administrator will want to compare the English and the translated language to ensure that the structure is identical (e.g. 2 notes vs 2 notes) and for a quick check on the content. (i.e. side by side compare)

Originally from @ReesePlews

**Comment by strogonoff** [comment]
Closing in favor of https://github.com/glossarist/glossarist-desktop/issues/48
