### ISSUE TITLE
Languages available do not match TC 211 MLGT

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#30]
The current list of languages available does not match the contents of MLGT (it matches IEV, though). We don't want translators creating new translations for languages that we do not have an existing responsible party for.

<img width="268" alt="Screen Shot 2020-06-25 at 9 56 20 PM" src="https://user-images.githubusercontent.com/11865/85733359-b4ec8700-b72e-11ea-8239-75e8c165cb7d.png">
<img width="239" alt="Screen Shot 2020-06-25 at 9 56 29 PM" src="https://user-images.githubusercontent.com/11865/85733387-b9b13b00-b72e-11ea-8e0f-d64de226bde4.png">

Originally from @ReesePlews

**Comment by strogonoff** [comment]
@ronaldtse Could I find a complete list of languages supported by ISO/TC 211?

**Comment by ronaldtse** [comment]
Sure, list is here: https://github.com/geolexica/isotc211-glossary/blob/master/tc211-termbase.meta.yaml

**Comment by strogonoff** [comment]
@ronaldtse The app now picks up available languages from `register.yaml` (https://github.com/geolexica/isotc211-glossary/pull/19). Any subregister for which the ID matches the ISO code of a language is treated as one of supported languages by Glossarist.

(Glossarist still provides the full mapping of language IDs to language names, this file is only used to determine which of those languages are to be available for viewing/translating concepts in given concept system.)

**Comment by ronaldtse** [comment]
@strogonoff thanks for the great news!
