### ISSUE TITLE
Automatic releases not working?

### ISSUE THREAD

**Issue by strogonoff** [glossarist/glossarist-desktop#35]
GitHub ran build/release workflow 1 hour ago, `package.json` specifies version 1.4.2 since yesterday but latest release is still at 1.4.1 🤔

**Comment by strogonoff** [comment]
Ping @ronaldtse, perhaps you know since the build works primarily thanks to you in the first place…

I don’t think the linter’s to blame, linter fails due to misconfiguration but build & release stage seems to succeed to the end. If lint stage really does prevent release from publication (which would be not obvious) I’d say we could probably disable lint since it currently does not work and while we fix and configure it properly we probably want automatic releases anyway

**Comment by ronaldtse** [comment]
From the build:
```
"  • uploading       file=Glossarist-1.4.2-mac.zip provider=GitHub
912
  • skipped publishing  file=Glossarist-1.4.2-mac.zip reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v1.4.2 version=1.4.2
913
  • skipped publishing  file=latest-mac.yml reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v1.4.2 version=1.4.2
914
```

Looks like the tag of `v1.4.2` wasn't created. To make a release, you need to git tag it.

**Comment by ronaldtse** [comment]
Working now, closing.
