### ISSUE TITLE
Some math not showing in the "concept summary" pane

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#38]
<img width="1247" alt="Screen Shot 2020-07-01 at 9 30 43 PM" src="https://user-images.githubusercontent.com/11865/86249841-62a1df00-bbe2-11ea-9c60-65094934611f.png">

**Comment by strogonoff** [comment]
The app expects math to be formatted [like this](https://github.com/riboseinc/iev-glossarist-data/blob/master/concepts/concept-1030106.yaml#L77). Formatting in isotc211-glossary [seems different](https://github.com/geolexica/isotc211-glossary/blob/master/concepts/concept-2455.yaml#L6).

@ronaldtse should data migration with math conversion be performed?

**Comment by ronaldtse** [comment]
> Formatting in isotc211-glossary seems different.

The isotc211-glossary format is the latest. The reason is the translator's ability to preview with MathJax from the Excel sheet.

Can we have a stopgap solution here, i.e. parse asciimath using \`..\` and latex math using `\(...\)` and `\[...\]`?

**Comment by strogonoff** [comment]
> stopgap solution 

From what I can see, we either break Glossarist for IEC or teach the app to support multiple ways of formatting math, with either auto-detection or from user configuration

**Comment by ronaldtse** [comment]
We can break IEC for now (since it's a pilot) and fix this in the importer later.

**Comment by strogonoff** [comment]
@phuonghuynh, could you take a look at how math is handled and whether we can quickly and easily make `react-mathjax2` (the library we use to render math) support the syntax on Ronald’s screenshot?

* MathJax context is configured here: https://github.com/glossarist/glossarist-desktop/blob/master/src/renderer/home/module.tsx#L159

* The file passed as `script` was obtained from MathJax.org. We keep MathJax distribution under `/src/static/math`.

**Comment by phuonghuynh** [comment]
Yes, @strogonoff

**Comment by ronaldtse** [comment]
Thanks guys!

**Comment by phuonghuynh** [comment]
@ronaldtse could you add me to isotc211-glossary DB to check this issue?

**Comment by ronaldtse** [comment]
Done, added.

**Comment by strogonoff** [comment]
Am closing this, since math is rendering now.

For now, long math lines make card and panel contents scroll. It is an open question whether long lines of math can be broken up in a way that does not interfere with their meaning. We may file another issue if we will want to deal with long lines better.
