### ISSUE TITLE
"Authoritative source" Link must be optional

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#40]
Not all concepts have an authoritative source link.

**Comment by strogonoff** [comment]
Isn’t there always a source (sources) at the beginning of a revision chain? Definitions do not materialize out of nothing.

I believe what should be done is restructuring how sources are handled.

1. Multiple sources should be possible to specify, for instances where a definition is created from original research.

2. We should not require a source to always be “authoritative”, as in some standard with a link.

**Comment by ronaldtse** [comment]
Not all authoritative sources have a URI "link".

**Comment by strogonoff** [comment]
I have re-read, right, “link” is the problem.

**Comment by strogonoff** [comment]
The link was made optional in https://github.com/glossarist/glossarist-desktop/commit/f502bda55a4a07f06ff56c741c96812d0d9edb3a
