### ISSUE TITLE
Store all time information in UTC

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#61]
From @strogonoff :

> this looks like a ticket for the desktop software which should apply current user’s local timezone adjustment when storing timestamps in Zulu/UTC (I think it currently doesn’t)

_Originally posted by @strogonoff in https://github.com/geolexica/isotc211-glossary/pull/17#issuecomment-653501395_

**Comment by ronaldtse** [comment]
@phuonghuynh can you help here? Thanks!

**Comment by strogonoff** [comment]
Duplicate of https://github.com/glossarist/glossarist-desktop/issues/50
