### ISSUE TITLE
Need to support multiple data repositories in the same app

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#98]
It is very difficult to switch repositories e.g. from ISO/TC 211 to OSGeo glossary or any new glossary. (the user needs to wipe out `Library/Application Support/Glossarist/*` to do so)

We need to have a "switch" to allow changing glossary repositories.

**Comment by strogonoff** [comment]
Closing as being addressed in https://github.com/paneron/paneron.
